name: Chore
description: 잡일 / 리팩토링 / 설정 변경
labels: ['chore']
body:
  - type: textarea
    id: task
    attributes:
      label: 작업 내용
      placeholder: 무엇을 할지 간단히
    validations:
      required: true
