export const SORT_OPTIONS = [
  { label: '최신순', value: 'latest' },
  { label: '좋아요순', value: 'likes' },
  { label: '마감임박순', value: 'deadline' },
] as const;

export const RECRUITMENT_TYPE_OPTIONS = [
  { label: '웹', value: 'web' },
  { label: '앱', value: 'app' },
  { label: '게임', value: 'game' },
  { label: 'AI / ML', value: 'ai' },
  { label: '오픈소스', value: 'opensource' },
  { label: '기타', value: 'etc' },
] as const;

export const ROLE_OPTIONS = [
  { label: '프론트엔드', value: 'frontend' },
  { label: '백엔드', value: 'backend' },
  { label: '풀스택', value: 'fullstack' },
  { label: 'iOS', value: 'ios' },
  { label: 'Android', value: 'android' },
  { label: 'UI/UX 디자이너', value: 'design' },
  { label: '기획자 (PM)', value: 'pm' },
  { label: '데이터 / ML', value: 'data' },
  { label: 'DevOps', value: 'devops' },
] as const;

// 직군(role)별 기술스택 — TechStackPopover 내부 1차/2차 분류에 사용
export const TECH_STACKS_BY_ROLE: Record<string, readonly string[]> = {
  frontend: [
    'React',
    'Next.js',
    'Vue',
    'Nuxt',
    'Angular',
    'Svelte',
    'TypeScript',
    'JavaScript',
    'Tailwind CSS',
    'Sass',
    'React Native',
    'Flutter',
    'Expo',
  ],
  backend: [
    'Node.js',
    'Express',
    'NestJS',
    'Spring',
    'Spring Boot',
    'Django',
    'FastAPI',
    'Flask',
    'Laravel',
    'Rails',
    'Go',
    'Rust',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'GraphQL',
    'tRPC',
    'REST API',
    'Prisma',
    'Drizzle',
  ],
  fullstack: [
    'Next.js',
    'Nuxt',
    'SvelteKit',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'PostgreSQL',
    'Supabase',
    'Firebase',
    'Prisma',
    'Drizzle',
    'Vercel',
    'AWS',
  ],
  ios: [
    'Swift',
    'SwiftUI',
    'UIKit',
    'Objective-C',
    'Xcode',
    'TestFlight',
    'Firebase',
    'Supabase',
  ],
  android: [
    'Kotlin',
    'Java',
    'Jetpack Compose',
    'XML',
    'Android Studio',
    'Firebase',
    'Supabase',
    'Retrofit',
    'Room',
  ],
  design: [
    'Figma',
    'Adobe XD',
    'Sketch',
    'Illustrator',
    'Photoshop',
    'After Effects',
    'Blender',
    'Zeplin',
    'Framer',
  ],
  pm: [
    'Notion',
    'Jira',
    'Confluence',
    'Figma',
    'Miro',
    'Google Analytics',
    'Amplitude',
    'Mixpanel',
  ],
  data: [
    'Python',
    'R',
    'PyTorch',
    'TensorFlow',
    'scikit-learn',
    'Keras',
    'Pandas',
    'NumPy',
    'Jupyter',
    'LangChain',
    'HuggingFace',
    'OpenAI',
    'Spark',
    'Airflow',
    'AWS SageMaker',
    'GCP Vertex AI',
  ],
  devops: [
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Azure',
    'GitHub Actions',
    'GitLab CI',
    'Jenkins',
    'Terraform',
    'Ansible',
    'Nginx',
    'Linux',
    'Prometheus',
    'Grafana',
  ],
};

// 모집종류(projectType)별 기술스택 — 기존 유지
export const TECH_STACKS_BY_TYPE: Record<string, readonly string[]> = {
  web: [
    'React',
    'Next.js',
    'Vue',
    'Nuxt',
    'Angular',
    'Svelte',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'Express',
    'NestJS',
    'Spring',
    'Django',
    'FastAPI',
    'Laravel',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Tailwind CSS',
    'Prisma',
    'Drizzle',
    'GraphQL',
    'tRPC',
    'Vercel',
    'AWS',
    'Docker',
  ],
  app: [
    'React Native',
    'Flutter',
    'Expo',
    'Swift',
    'SwiftUI',
    'Kotlin',
    'Jetpack Compose',
    'TypeScript',
    'Dart',
    'Firebase',
    'Supabase',
    'AWS Amplify',
    'Riverpod',
    'MobX',
    'Zustand',
  ],
  game: [
    'Unity',
    'Unreal Engine',
    'Godot',
    'C#',
    'C++',
    'GDScript',
    'Blender',
    'Photoshop',
    'WebGL',
    'Three.js',
    'Phaser',
  ],
  ai: [
    'Python',
    'PyTorch',
    'TensorFlow',
    'scikit-learn',
    'Keras',
    'OpenAI',
    'LangChain',
    'HuggingFace',
    'FastAPI',
    'Flask',
    'Pandas',
    'NumPy',
    'Jupyter',
    'Docker',
    'Kubernetes',
    'AWS SageMaker',
  ],
  opensource: [
    'TypeScript',
    'JavaScript',
    'Python',
    'Go',
    'Rust',
    'Java',
    'GitHub Actions',
    'Docker',
    'Node.js',
    'React',
    'Vue',
  ],
  etc: [
    'TypeScript',
    'JavaScript',
    'Python',
    'Go',
    'Rust',
    'Java',
    'C#',
    'C++',
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Azure',
    'Figma',
    'Notion',
  ],
};

export const ALL_TECH_STACKS = [
  ...new Set([
    ...Object.values(TECH_STACKS_BY_TYPE).flat(),
    ...Object.values(TECH_STACKS_BY_ROLE).flat(),
  ]),
].sort();

export {
  RECRUITMENT_HEADCOUNT_MIN as MIN_HEADCOUNT,
  RECRUITMENT_HEADCOUNT_MAX as MAX_HEADCOUNT,
} from './recruitment';

export type SortValue = (typeof SORT_OPTIONS)[number]['value'];
export type RecruitmentTypeValue =
  (typeof RECRUITMENT_TYPE_OPTIONS)[number]['value'];
export type RoleValue = (typeof ROLE_OPTIONS)[number]['value'];
